[project]
name = "imagematcher"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "fastapi>=0.120.0",
    "opencv-contrib-python>=4.12.0.88",
    "python-multipart>=0.0.20",
    "uvicorn>=0.38.0",
]
